spring.application.name=OnlineFoodApp
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/nomzee
spring.datasource.username=root
spring.datasource.password=d3bayan@mysql

# JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Email Settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anujaghosal@gmail.com
spring.mail.password=nbcbsandjunsivgx

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Razorpay Keys
razorpay.key.id=rzp_test_SjAnmZ65GMFkE1
razorpay.key.secret=FlR9iL5FeeB4r1VAuaS7yiMu